Fixing lack of has_disk? in vcloud cpi.
Likely to need to be added to other non implemented methods by vcloud_cpi

Fails cloud check:

$ bosh cloudcheck
Performing cloud check...
[...]
  Started scanning 1 persistent disks > Looking for inactive disks. Failed: undefined method `has_disk?' for #<Bosh::Clouds::VCloud:0x000000033a7ed0> (00:00:00)

The full strack trace provided by "bosh task --debug" is:

D, [2014-10-06T07:28:14.133187 #13564] [task:179] DEBUG -- : Deleted lock: lock:deployment:bosh-appsdev-vdr-qa
E, [2014-10-06T07:28:14.133706 #13564] [task:179] ERROR -- : undefined method `has_disk?' for #<Bosh::Clouds::VCloud:0x000000049d2cc8>
/var/vcap/packages/director/gem_home/ruby/1.9.1/gems/bosh-director-1.2710.0/lib/bosh/director/problem_scanner/disk_scan_stage.rb:38:in `scan_disk'
/var/vcap/packages/director/gem_home/ruby/1.9.1/gems/bosh-director-1.2710.0/lib/bosh/director/problem_scanner/disk_scan_stage.rb:23:in `block (2 levels) in scan'
/var/vcap/packages/director/gem_home/ruby/1.9.1/gems/bosh-director-1.2710.0/lib/bosh/director/problem_scanner/disk_scan_stage.rb:22:in `each'
/var/vcap/packages/director/gem_home/ruby/1.9.1/gems/bosh-director-1.2710.0/lib/bosh/director/problem_scanner/disk_scan_stage.rb:22:in `block in scan'
/var/vcap/packages/director/gem_home/ruby/1.9.1/gems/bosh-director-1.2710.0/lib/bosh/director/problem_scanner/scanner.rb:81:in `block in track_and_log'
/var/vcap/packages/director/gem_home/ruby/1.9.1/gems/bosh-director-1.2710.0/lib/bosh/director/event_log.rb:83:in `call'
/var/vcap/packages/director/gem_home/ruby/1.9.1/gems/bosh-director-1.2710.0/lib/bosh/director/event_log.rb:83:in `advance_and_track'
/var/vcap/packages/director/gem_home/ruby/1.9.1/gems/bosh-director-1.2710.0/lib/bosh/director/event_log.rb:36:in `track'
/var/vcap/packages/director/gem_home/ruby/1.9.1/gems/bosh-director-1.2710.0/lib/bosh/director/problem_scanner/scanner.rb:79:in `track_and_log'
/var/vcap/packages/director/gem_home/ruby/1.9.1/gems/bosh-director-1.2710.0/lib/bosh/director/problem_scanner/disk_scan_stage.rb:21:in `scan'
/var/vcap/packages/director/gem_home/ruby/1.9.1/gems/bosh-director-1.2710.0/lib/bosh/director/problem_scanner/scanner.rb:63:in `scan_disks'
/var/vcap/packages/director/gem_home/ruby/1.9.1/gems/bosh-director-1.2710.0/lib/bosh/director/jobs/cloud_check/scan.rb:27:in `block in perform'
/var/vcap/packages/director/gem_home/ruby/1.9.1/gems/bosh-director-1.2710.0/lib/bosh/director/lock_helper.rb:21:in `block in with_deployment_lock'
/var/vcap/packages/director/gem_home/ruby/1.9.1/gems/bosh-director-1.2710.0/lib/bosh/director/lock.rb:58:in `lock'
/var/vcap/packages/director/gem_home/ruby/1.9.1/gems/bosh-director-1.2710.0/lib/bosh/director/lock_helper.rb:21:in `with_deployment_lock'
/var/vcap/packages/director/gem_home/ruby/1.9.1/gems/bosh-director-1.2710.0/lib/bosh/director/jobs/cloud_check/scan.rb:23:in `perform'
/var/vcap/packages/director/gem_home/ruby/1.9.1/gems/bosh-director-1.2710.0/lib/bosh/director/job_runner.rb:104:in `perform_job'
/var/vcap/packages/director/gem_home/ruby/1.9.1/gems/bosh-director-1.2710.0/lib/bosh/director/job_runner.rb:31:in `block in run'
/var/vcap/packages/director/gem_home/ruby/1.9.1/gems/bosh_common-1.2710.0/lib/common/thread_formatter.rb:46:in `with_thread_name'
/var/vcap/packages/director/gem_home/ruby/1.9.1/gems/bosh-director-1.2710.0/lib/bosh/director/job_runner.rb:31:in `run'
/var/vcap/packages/director/gem_home/ruby/1.9.1/gems/bosh-director-1.2710.0/lib/bosh/director/jobs/base_job.rb:10:in `perform'
/var/vcap/packages/director/gem_home/ruby/1.9.1/gems/resque-1.25.2/lib/resque/job.rb:227:in `perform'
/var/vcap/packages/director/gem_home/ruby/1.9.1/gems/resque-1.25.2/lib/resque/worker.rb:250:in `perform'
/var/vcap/packages/director/gem_home/ruby/1.9.1/gems/resque-1.25.2/lib/resque/worker.rb:189:in `block in work'
/var/vcap/packages/director/gem_home/ruby/1.9.1/gems/resque-1.25.2/lib/resque/worker.rb:166:in `loop'
/var/vcap/packages/director/gem_home/ruby/1.9.1/gems/resque-1.25.2/lib/resque/worker.rb:166:in `work'
/var/vcap/packages/director/gem_home/ruby/1.9.1/gems/bosh-director-1.2710.0/bin/bosh-director-worker:78:in `<top (required)>'
/var/vcap/packages/director/bin/bosh-director-worker:16:in `load'
/var/vcap/packages/director/bin/bosh-director-worker:16:in `<main>'